[workspace]
resolver = "2"
members = [
  "crates/server",
  "crates/agent",
  "crates/core",
  "crates/protocol",
]

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uuid = { version = "1", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
