[package]
name = "healthcheck-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "healthcheck"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap.workspace = true
healthcheck-core = { path = "../core" }
reqwest.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
